services:
  backend:
    image: ${BACKEND_IMAGE_URI}  # This will use the BACKEND_IMAGE_URI environment variable
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend.env
    environment:
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  frontend:
    image: ${FRONTEND_IMAGE_URI}  # This will use the FRONTEND_IMAGE_URI environment variable
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - ./frontend.env
    depends_on:
      - backend
    environment:
      - VITE_PUBLIC_API_URL=${VITE_PUBLIC_API_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
