services:
  backend:
    image: your-dockerhub-username/springboot-app:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  frontend:
    image: your-dockerhub-username/react-vite-app:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_PUBLIC_API_URL=${VITE_PUBLIC_API_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
